name: quality_control
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- bwa
- samtools
- pigz
- fastqc
- sambamba
- graphviz
- multiqc
- pulp>=2.8
- pip:
  - sequana
  - cutadapt
  - atropos
