[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "sequana-quality-control"
version = "1.3.0"
description = "Quality control pipeline for NGS data (phix removal, adapter trimming, FastQC)"
authors = ["Sequana Team"]
license = "BSD-3"
repository = "https://github.com/sequana/quality_control"
readme = "README.rst"
keywords = ["snakemake", "NGS", "sequana", "fastqc", "cutadapt", "multiqc"]
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Education",
        "Intended Audience :: End Users/Desktop",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: BSD License",
        "Operating System :: POSIX :: Linux",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Topic :: Scientific/Engineering :: Information Analysis",
]

packages = [
    {include = "sequana_pipelines"}
]


[tool.poetry.dependencies]
python = ">=3.9,<4.0"
sequana = ">=0.24.1"
sequana_pipetools = ">=1.1.1"
sequana-wrappers = ">=26.4.16"
snakemake = ">=7.32"
pulp = ">=2.8"
click = "^8.1.7"
rich-click = "^1.7.2"
cutadapt = ">4.6"

[tool.poetry.scripts]
sequana_quality_control = "sequana_pipelines.quality_control.main:main"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pytest = "^7.4.0"
mock = "^5.1.0"
pytest-mock = "^3.11.1"
pytest-cov = "^4.1.0"
