# ============================================================================
# Config file for Quality Control
# ==========================================[ Sections for the users ]========
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# ============================================================================
input_directory: /home/cokelaer/Data/Hm2
input_readtag: _R[12]_
input_pattern: '*fastq.gz'
reference_file: phiX174.fa


apptainers:
    pigz: https://zenodo.org/record/7346805/files/pigz_2.4.0.img
    fastqc: https://zenodo.org/record/7015004/files/fastqc_0.11.9-py3.img
    bwa: https://zenodo.org/record/7970243/files/bwa_0.7.17.img
    graphviz: https://zenodo.org/record/7928262/files/graphviz_7.0.5.img
    sequana_tools: https://zenodo.org/record/7963917/files/sequana_tools_0.15.1.img

#############################################################################
# BWA used to remove a contaminant
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored
# - reference_file: the name of the reference file to be found
#        in the analysis directory. If set to phiX174.fa,
#        it is downloaded automatically from Sequana, otherwise you will
#        need to copy it yourself in the working directory.
# - index_algorithm: the BWA index algorithm
# - options: any options recognised by BWA tool
# - threads: number of threads to be used
bwa_mem_phix:
    do: true
    index_algorithm: is
    options: -T 30
    threads: 4
    tmp_directory: ./tmp




#######################################################################
# Quality trimming and adapter removal
#
# For adapter removal, the fwd and rev fields are used. It can be a
# string, or a filename. If a filename, it must be prefixed with "file:" to
# specify that it is a file and not a string. If the tool is cutadapt, the empty
# fwd and rev fields means that no adapters are to be used.
#
# :Parameters:
#
# - fwd: a string or file (prefixed with *file:*)
# - m: 20 means discard trimmed reads that are shorter than 20.
#         must be > 0
# - quality: 0 means no trimming, 30 means keep base with quality
#        above 30
# - mode: must be set to one of
#     - g for 5'
#     - a for 3'
#     - b for both 5'/3'
# - rev: a string or file (prefixed with *file:*)
# - tool: only cutadapt supported for now
# - threads: number of threads to use (atropos only)
# - options: See cutadapt documentation for details on
#            cutadapt.readthedocs.io. We change the default value
#            of -O to 6 (at least 6 bases are required to match before
#            trimming of an adapter)
#
# tool_choice__ = ["atropos", "cutadapt"]
cutadapt:
    do: true
    fwd: ''
    rev: ''
    m: 20
    mode: b
    options: ' -O 6 --trim-n'
    quality: 30
    threads: 4




# sofware__choice = ["atropos", "cutadapt"]
trimming:
    software_choice: cutadapt
    do: true


#################################################################
# FastQC section
#
# :Parameters:
#
# - options: string with any valid FastQC options
# - do_raw: performs fastqc on raw data
# - do_after_adapter_removal: performs fastqc on data after
#   adapter removal
# - do_after_phix_removal: performs fastqc on data without phix
fastqc:
    options: --nogroup
    threads: 4
    do_raw: true
    do_after_phix_removal: true
    do_after_adapter_removal: true


fastq_stats:
    max_reads: 500000
