# Schema validator for the quality_control
# author: Thomas Cokelaer

type: map
mapping:
    "input_directory":
        type: str
        required: False
    "input_readtag":
        type: str
        required: False
    "input_pattern":
        type: str
        required: False
    "reference_file":
        type: str
        required: True
        pattern: .*

    "bwa_mem_phix":
        type: map
        mapping:
            "do":
                type: bool
                default: True
            "index_algorithm":
                type: str
                required: False
                default: "is"
            "options":
                type: str
                default: "-T 30"
                required: False
            "threads":
                type: int
                required: True
                range: { min: 1, max: 8 }
            "tmp_directory":
                type: str
                required: True
                default: './tmp'
                pattern: .*

    "trimming":
        type: map
        mapping:
          "software_choice":
            type: str
            enum: ["atropos", "cutadapt"]
          "do":
            type: bool
    

    "fastq_stats":
        type: map
        mapping:
          "max_reads":
            type: int
            required: True
            range: { min: 1 }


    "fastqc":
        type: map
        mapping:
            "options":
                type: str
                required: False
            "do_raw":
                type: bool
            "do_after_phix_removal":
                type: bool
            "do_after_adapter_removal":
                type: bool
            "threads":
                type: int
                required: True
                range: { min: 1 }

    "cutadapt":
        type: map
        mapping:
            "do":
                type: bool
                required: True
            "tool_choice":
                type: str
                enum: [cutadapt,atropos]
                required: True
            "fwd":
                type: str
                required: False
            "rev":
                type: str
                required: False
            "m":
                type: int
                range: {min: 0}
                required: True
            "mode":
                type: str
                enum: [b, g, a]
                required: True
            "options":
                type: str
                required: False
            "quality":
                type: int
                range: {max: 40, min: 0}
                required: False
            "threads":
                type: int
                required: True
                range: { min: 1 }







